/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shaltout.hospital.view;

import com.shaltout.hospital.db.model.PatientInfo;
import com.shaltout.hospital.db.model.User;

/**
 *
 * @author ahmed
 */
public class Home extends javax.swing.JFrame {

    public static User user;

    /**
     * Creates new form Home
     * @param user
     */
    public Home(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        getUserLevel();
    }

    protected void getUserLevel(){
        switch(user.getUserType().getType()){
            case "admin":
                mDoctor.setEnabled(false);
                mNurse.setEnabled(false);
                mReceptionist.setEnabled(false);
                break;
            case "doctor":
                mAdmin.setEnabled(false);
                mNurse.setEnabled(false);
                mReceptionist.setEnabled(false);
                break;
            case "nurse":
                mDoctor.setEnabled(false);
                mAdmin.setEnabled(false);
                mReceptionist.setEnabled(false);
                break;
            case "reception":
                mDoctor.setEnabled(false);
                mNurse.setEnabled(false);
                mAdmin.setEnabled(false);
                break;
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAdmin = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mDoctor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mReceptionist = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mNurse = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ahmed/NetBeansProjects/HospitalSystem/Images/Webp.net-resizeimage.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 900));

        mAdmin.setText("Admin");

        jMenuItem1.setText("Users");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mAdmin.add(jMenuItem1);

        jMenuBar1.add(mAdmin);

        mDoctor.setText("Doctor");

        jMenuItem3.setText("Patient Info");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mDoctor.add(jMenuItem3);

        jMenuBar1.add(mDoctor);

        mReceptionist.setText("Receptionist");

        jMenuItem2.setText("patient info");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mReceptionist.add(jMenuItem2);

        jMenuBar1.add(mReceptionist);

        mNurse.setText("Nurse");

        jMenuItem4.setText("Patient Info");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mNurse.add(jMenuItem4);

        jMenuBar1.add(mNurse);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new UsersView();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        PatientInfoView patientInfoView = new PatientInfoView();
        patientInfoView.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MessageView messageView = new MessageView();
        messageView.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MessageView messageView = new MessageView();
        messageView.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mAdmin;
    private javax.swing.JMenu mDoctor;
    private javax.swing.JMenu mNurse;
    private javax.swing.JMenu mReceptionist;
    // End of variables declaration//GEN-END:variables

}
